######################################################################
# Automatically generated by qmake (2.01a) Wed Oct 31 16:41:23 2012
######################################################################

TEMPLATE = app
TARGET = computerSim.exe
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += assembly.h mainwindow.h
FORMS += mainwindow.ui
SOURCES += assembly.cpp main.cpp mainwindow.cpp
