######################################################################
# Automatically generated by qmake (2.01a) Wed Dec 12 15:19:54 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ComputerSim.h mainwindow.h utils_export.h
FORMS += mainwindow.ui
SOURCES += ComputerSim.cpp main.cpp mainwindow.cpp
