######################################################################
# Automatically generated by qmake (2.01a) Wed Oct 3 11:31:54 2012
######################################################################

TEMPLATE = app
TARGET = dictionaryGUI.exe
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += dictionary.h mainwindow.h
FORMS += mainwindow.ui
SOURCES += dictionary.cpp main.cpp mainwindow.cpp
