######################################################################
# Automatically generated by qmake (2.01a) Mon Sep 10 16:24:52 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += reslist.h
SOURCES += main.cpp reslist.cpp
