######################################################################
# Automatically generated by qmake (2.01a) Fri Sep 21 01:56:45 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
INCLUDEPATH += ../src

# Input
SOURCES += main.cpp
SOURCES += ../src/Dictionary.cpp
