######################################################################
# Automatically generated by qmake (2.01a) Fri Oct 19 18:01:11 2012
######################################################################

TEMPLATE = app
TARGET = computerSim.exe
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += assembly.h mainwindow.h
FORMS += mainwindow.ui
SOURCES += assembly.cpp main.cpp mainwindow.cpp
